// Date: 6/9/2013 7:00:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.manarz.entity.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelGnats extends ModelBase
{
  //fields
    ModelRenderer g0;
    ModelRenderer a;
    ModelRenderer g1;
    ModelRenderer g2;
    ModelRenderer g3;
    ModelRenderer g4;
    ModelRenderer g5;
    ModelRenderer g6;
    ModelRenderer g7;
    ModelRenderer g8;
    ModelRenderer g9;
    ModelRenderer g10;
    ModelRenderer g11;
    ModelRenderer g12;
    ModelRenderer g13;
    ModelRenderer g14;
    ModelRenderer g15;
    ModelRenderer b;
    ModelRenderer c;
    ModelRenderer d;
    ModelRenderer e;
    ModelRenderer ax;
    ModelRenderer g;
    ModelRenderer h;
    ModelRenderer i;
    ModelRenderer j;
    ModelRenderer k;
    ModelRenderer l;
    ModelRenderer m;
    ModelRenderer n;
    ModelRenderer o;
    ModelRenderer p;
    ModelRenderer q;
  
  public ModelGnats()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      g0 = new ModelRenderer(this, 0, 0);
      g0.addBox(0F, 0F, 0F, 2, 2, 6);
      g0.setRotationPoint(2F, 9F, 7F);
      g0.setTextureSize(64, 32);
      g0.mirror = true;
      setRotation(g0, 0F, 0F, 0F);
      a = new ModelRenderer(this, 16, 0);
      a.addBox(0F, 0F, 0F, 8, 0, 2);
      a.setRotationPoint(-3F, 0F, 2F);
      a.setTextureSize(64, 32);
      a.mirror = true;
      setRotation(a, 0.0872665F, 0F, 0F);
      g1 = new ModelRenderer(this, 0, 8);
      g1.addBox(0F, 0F, 0F, 2, 2, 6);
      g1.setRotationPoint(0F, 0F, 0F);
      g1.setTextureSize(64, 32);
      g1.mirror = true;
      setRotation(g1, 0F, 0F, 0F);
      g2 = new ModelRenderer(this, 0, 16);
      g2.addBox(0F, 0F, 0F, 2, 2, 6);
      g2.setRotationPoint(2F, 14F, 11F);
      g2.setTextureSize(64, 32);
      g2.mirror = true;
      setRotation(g2, 0F, 0F, 0F);
      g3 = new ModelRenderer(this, 0, 8);
      g3.addBox(0F, 0F, 0F, 2, 2, 6);
      g3.setRotationPoint(7F, 13F, -2F);
      g3.setTextureSize(64, 32);
      g3.mirror = true;
      setRotation(g3, 0F, 0F, 0F);
      g4 = new ModelRenderer(this, 0, 0);
      g4.addBox(0F, 0F, 0F, 2, 2, 6);
      g4.setRotationPoint(9F, 9F, 5F);
      g4.setTextureSize(64, 32);
      g4.mirror = true;
      setRotation(g4, 0F, 0F, 0F);
      g5 = new ModelRenderer(this, 0, 8);
      g5.addBox(0F, 0F, 0F, 2, 2, 6);
      g5.setRotationPoint(-2F, 5F, 1F);
      g5.setTextureSize(64, 32);
      g5.mirror = true;
      setRotation(g5, 0F, 0F, 0F);
      g6 = new ModelRenderer(this, 0, 8);
      g6.addBox(0F, 0F, 0F, 2, 2, 6);
      g6.setRotationPoint(-5F, 16F, -5F);
      g6.setTextureSize(64, 32);
      g6.mirror = true;
      setRotation(g6, 0F, 0F, 0F);
      g7 = new ModelRenderer(this, 0, 8);
      g7.addBox(0F, 0F, 0F, 2, 2, 6);
      g7.setRotationPoint(-1F, 10F, -3F);
      g7.setTextureSize(64, 32);
      g7.mirror = true;
      setRotation(g7, 0F, 0F, 0F);
      g8 = new ModelRenderer(this, 0, 16);
      g8.addBox(0F, 1F, 0F, 2, 2, 6);
      g8.setRotationPoint(8F, 4F, -7F);
      g8.setTextureSize(64, 32);
      g8.mirror = true;
      setRotation(g8, 0F, 0F, 0F);
      g9 = new ModelRenderer(this, 0, 16);
      g9.addBox(0F, 0F, 0F, 2, 2, 6);
      g9.setRotationPoint(-8F, 6F, 9F);
      g9.setTextureSize(64, 32);
      g9.mirror = true;
      setRotation(g9, 0F, 0F, 0F);
      g10 = new ModelRenderer(this, 0, 0);
      g10.addBox(0F, 0F, 0F, 2, 2, 6);
      g10.setRotationPoint(-6F, 12F, 8F);
      g10.setTextureSize(64, 32);
      g10.mirror = true;
      setRotation(g10, 0F, 0F, 0F);
      g11 = new ModelRenderer(this, 0, 16);
      g11.addBox(0F, 0F, 0F, 2, 2, 6);
      g11.setRotationPoint(4F, 17F, 0F);
      g11.setTextureSize(64, 32);
      g11.mirror = true;
      setRotation(g11, 0F, 0F, 0F);
      g12 = new ModelRenderer(this, 0, 8);
      g12.addBox(0F, 0F, 0F, 2, 2, 6);
      g12.setRotationPoint(3F, 2F, -5F);
      g12.setTextureSize(64, 32);
      g12.mirror = true;
      setRotation(g12, 0F, 0F, 0F);
      g13 = new ModelRenderer(this, 0, 16);
      g13.addBox(0F, 0F, 0F, 2, 2, 6);
      g13.setRotationPoint(-7F, 3F, -2F);
      g13.setTextureSize(64, 32);
      g13.mirror = true;
      setRotation(g13, 0F, 0F, 0F);
      g14 = new ModelRenderer(this, 0, 16);
      g14.addBox(0F, 0F, 0F, 2, 2, 6);
      g14.setRotationPoint(2F, 5F, -1F);
      g14.setTextureSize(64, 32);
      g14.mirror = true;
      setRotation(g14, 0F, 0F, 0F);
      g15 = new ModelRenderer(this, 0, 16);
      g15.addBox(0F, 0F, 0F, 2, 2, 6);
      g15.setRotationPoint(3F, 11F, -2F);
      g15.setTextureSize(64, 32);
      g15.mirror = true;
      setRotation(g15, 0F, 0F, 0F);
      b = new ModelRenderer(this, 16, 2);
      b.addBox(0F, 0F, 0F, 8, 0, 2);
      b.setRotationPoint(0F, 2F, -3F);
      b.setTextureSize(64, 32);
      b.mirror = true;
      setRotation(b, 0.0872665F, 0F, 0F);
      c = new ModelRenderer(this, 16, 0);
      c.addBox(0F, 0F, 0F, 8, 0, 2);
      c.setRotationPoint(-10F, 3F, 0F);
      c.setTextureSize(64, 32);
      c.mirror = true;
      setRotation(c, 0.0872665F, 0F, 0F);
      d = new ModelRenderer(this, 16, 0);
      d.addBox(-1F, 0F, 0F, 8, 0, 2);
      d.setRotationPoint(2F, 17F, 2F);
      d.setTextureSize(64, 32);
      d.mirror = true;
      setRotation(d, 0.0872665F, 0F, 0F);
      e = new ModelRenderer(this, 16, 4);
      e.addBox(0F, 0F, 0F, 8, 0, 2);
      e.setRotationPoint(5F, 5F, -5F);
      e.setTextureSize(64, 32);
      e.mirror = true;
      setRotation(e, 0.0872665F, 0F, 0F);
      ax = new ModelRenderer(this, 16, 2);
      ax.addBox(0F, 0F, 0F, 8, 0, 2);
      ax.setRotationPoint(-1F, 14F, 13F);
      ax.setTextureSize(64, 32);
      ax.mirror = true;
      setRotation(ax, 0.0872665F, 0F, 0F);
      g = new ModelRenderer(this, 16, 0);
      g.addBox(0F, 0F, 0F, 8, 0, 2);
      g.setRotationPoint(0F, 11F, 0F);
      g.setTextureSize(64, 32);
      g.mirror = true;
      setRotation(g, 0.0872665F, 0F, 0F);
      h = new ModelRenderer(this, 16, 0);
      h.addBox(0F, 0F, 0F, 8, 0, 2);
      h.setRotationPoint(4F, 13F, -1F);
      h.setTextureSize(64, 32);
      h.mirror = true;
      setRotation(h, 0.0872665F, 0F, 0F);
      i = new ModelRenderer(this, 16, 0);
      i.addBox(0F, 0F, 0F, 8, 0, 2);
      i.setRotationPoint(-1F, 5F, 0F);
      i.setTextureSize(64, 32);
      i.mirror = true;
      setRotation(i, 0.0872665F, 0F, 0F);
      j = new ModelRenderer(this, 16, 0);
      j.addBox(0F, 0F, 0F, 8, 0, 2);
      j.setRotationPoint(-1F, 9F, 9F);
      j.setTextureSize(64, 32);
      j.mirror = true;
      setRotation(j, 0.0872665F, 0F, 0F);
      k = new ModelRenderer(this, 16, 0);
      k.addBox(0F, 0F, 0F, 8, 0, 2);
      k.setRotationPoint(6F, 9F, 7F);
      k.setTextureSize(64, 32);
      k.mirror = true;
      setRotation(k, 0.0872665F, 0F, 0F);
      l = new ModelRenderer(this, 16, 0);
      l.addBox(0F, 0F, 0F, 8, 0, 2);
      l.setRotationPoint(-4F, 10F, -1F);
      l.setTextureSize(64, 32);
      l.mirror = true;
      setRotation(l, 0.0872665F, 0F, 0F);
      m = new ModelRenderer(this, 16, 0);
      m.addBox(0F, 0F, 0F, 8, 0, 2);
      m.setRotationPoint(-11F, 6F, 11F);
      m.setTextureSize(64, 32);
      m.mirror = true;
      setRotation(m, 0.0872665F, 0F, 0F);
      n = new ModelRenderer(this, 16, 0);
      n.addBox(0F, 0F, 0F, 8, 0, 2);
      n.setRotationPoint(-8F, 16F, -3F);
      n.setTextureSize(64, 32);
      n.mirror = true;
      setRotation(n, 0.0872665F, 0F, 0F);
      o = new ModelRenderer(this, 16, 0);
      o.addBox(0F, 0F, 0F, 8, 0, 2);
      o.setRotationPoint(-5F, 5F, 2F);
      o.setTextureSize(64, 32);
      o.mirror = true;
      setRotation(o, 0.0872665F, 0F, 0F);
      p = new ModelRenderer(this, 16, 4);
      p.addBox(0F, 0F, 0F, 8, 0, 2);
      p.setRotationPoint(-9F, 12F, 10F);
      p.setTextureSize(64, 32);
      p.mirror = true;
      setRotation(p, 0.0872665F, 0F, 0F);
      q = new ModelRenderer(this, 16, 0);
      q.addBox(0F, 0F, 0F, 8, 0, 2);
      q.setRotationPoint(-9F, 12F, 9F);
      q.setTextureSize(64, 32);
      q.mirror = true;
      setRotation(q, 0.0872665F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    g0.render(f5);
    a.render(f5);
    g1.render(f5);
    g2.render(f5);
    g3.render(f5);
    g4.render(f5);
    g5.render(f5);
    g6.render(f5);
    g7.render(f5);
    g8.render(f5);
    g9.render(f5);
    g10.render(f5);
    g11.render(f5);
    g12.render(f5);
    g13.render(f5);
    g14.render(f5);
    g15.render(f5);
    b.render(f5);
    c.render(f5);
    d.render(f5);
    e.render(f5);
    ax.render(f5);
    g.render(f5);
    h.render(f5);
    i.render(f5);
    j.render(f5);
    k.render(f5);
    l.render(f5);
    m.render(f5);
    n.render(f5);
    o.render(f5);
    p.render(f5);
    q.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
